apiVersion: v1
kind: Secret
metadata:
  name: azdevops
  namespace: azure-agent
data:
  AZP_URL: aHR0cHM6Ly9kZXYuYXp1cmUuY29tL2tzYXp1cmUx # https://dev.azure.com/houssemdellai
  AZP_POOL: a3ViZXJuZXRlc2FnZW50 # linux-containers-aks
  AZP_TOKEN: eWRwdW83eW94aHA0ZnhvN2dpZmRwb2Jnc3VncnNwNXhnb2U3ZjdzeGFwNXZlaXl4cTJyYQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: azure-agent
  labels:
    app: azdevops-agent
spec:
  replicas: 2 #here is the configuration for the actual agent always running
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: cophill/dockeragent
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock